POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2YTRiOWVmMzkzOTE1ZWUwY2M4Yjg0YWUiLCJpYXQiOjE3ODMzNDI1MjJ9.8EjjZGM1nPoa9Dvbq1nVKZN9L4NwIphRjNiGjxTtcUU

{
    "title": "Testing",
    "author": "John Doe",
    "url": "https://example.com",
    "likes": 10
}